// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEgUdESomb5whgZ-rGdSRxsqmxDVnnnjM',
    appId: '1:616831820760:web:2685d9fe3b1560fb4488ad',
    messagingSenderId: '616831820760',
    projectId: 'ngabsenin1',
    authDomain: 'ngabsenin1.firebaseapp.com',
    storageBucket: 'ngabsenin1.appspot.com',
    measurementId: 'G-XVFX8WTX05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbV9XUZxZT5rCjpvmDMft27PoJMCArDys',
    appId: '1:616831820760:android:7cc4955483d067ef4488ad',
    messagingSenderId: '616831820760',
    projectId: 'ngabsenin1',
    storageBucket: 'ngabsenin1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMMYOtytN_r0k3ywic7YWFnBxwhADYjNs',
    appId: '1:616831820760:ios:5934264c2df495864488ad',
    messagingSenderId: '616831820760',
    projectId: 'ngabsenin1',
    storageBucket: 'ngabsenin1.appspot.com',
    iosBundleId: 'com.example.proj1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMMYOtytN_r0k3ywic7YWFnBxwhADYjNs',
    appId: '1:616831820760:ios:5934264c2df495864488ad',
    messagingSenderId: '616831820760',
    projectId: 'ngabsenin1',
    storageBucket: 'ngabsenin1.appspot.com',
    iosBundleId: 'com.example.proj1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEgUdESomb5whgZ-rGdSRxsqmxDVnnnjM',
    appId: '1:616831820760:web:9868b00f852f17d94488ad',
    messagingSenderId: '616831820760',
    projectId: 'ngabsenin1',
    authDomain: 'ngabsenin1.firebaseapp.com',
    storageBucket: 'ngabsenin1.appspot.com',
    measurementId: 'G-0HZS5238EL',
  );
}
